export const config = {
  AUTH0_DOMAIN: process.env.NEXT_PUBLIC_AUTH0_DOMAIN,
  AUTH0_CLIENT_ID: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID,
  AUTH0_REDIRECT_URI:
    process.env.NEXT_PUBLIC_AUTH0_REDIRECT_URI ||
    (typeof document !== "undefined" && document.location.origin) ||
    undefined,
  MOJITO_API_URL: process.env.NEXT_PUBLIC_MOJITO_API_URL,
  MOJITO_API_WS_URL: process.env.NEXT_PUBLIC_MOJITO_API_WS_URL,
  ORGANIZATION_ID: process.env.NEXT_PUBLIC_API_ORGANIZATION_ID,
  MARKETPLACE_ID: process.env.NEXT_PUBLIC_MARKETPLACE_ID,
  ETH_VALUE_MULTIPLIER: parseInt(process.env.NEXT_PUBLIC_ETH_VALUE_MULTIPLIER!),
  COLLECTION_SLUG: process.env.NEXT_PUBLIC_COLLECTION_SLUG!,
};

export const TERMS_AND_CONDITIONS_LINK = "/";
