import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery } from "@apollo/client";

import QUERY_COUNTENFULL from "./queriesContentfull.graphql";

const Home: NextPage = () => {
  const { data, loading, error } = useQuery(QUERY_COUNTENFULL);

  
  // check for errors
  if (error) {
    return <p>:( an error happened</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Metaverso NFTs
        </h1>

        <p className={styles.description}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.
        </p>

        <div className={styles.grid}>
          {data?.lotCollection?.items.map((item) => (
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>{item.title}</h2>
              <p>{item.author.name}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
